apiVersion: apps/v1
kind: Deployment
metadata:
  name: proyectofinal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proyectofinal
  template:
    metadata:
      labels:
        app: proyectofinal
    spec:
      containers:
      - name: proyectofinal
        image: cursodvops/proyectofinal
        ports:
        - containerPort: 7000