apiVersion: v1
kind: Service
metadata:
  name: proyectofinal-service
  namespace: proyectofinal-namespace
spec:
  type: NodePort
  selector:
    app: proyectofinal-deployment
  ports:
      - nodePort: 30000
        port: 7000
        targetPort: 7000